name: KitchenSink
version: 0.4
author: Travis Watkins
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard]
permissions:
    kitchensink.list:
        description: List online players
        default: true
    kitchensink.lag:
        description: Show lag stats
        default: op
    kitchensink.unenchant:
        description: Remove enchants from current item
        default: op
    kitchensink.ksinventory:
        description: Edit a players inventory
        default: op
    kitchensunk.petadmin:
        description: Bypass ownership test in /unlock-horse, /lock-horse and /untame.
        default: op
        
description: 

commands:
    unenchant:
        description: Remove enchants from current item
        permission: kitchensink.unenchant
    lag:
        description: Get current TPS and memory stats
    list:
        description: List currently online players
        permission: kitchensink.list
        usage: |
           /list: Show online players
    ksinventory:
        description: Edit a players inventory
        permission: kitchensink.ksinventory
        usage: |
           /ksinventory <player> [clear]: Edit a players inventory
    painting:
        description: Allows selection of the next painting placed.
        usage: |
            /painting [<name>]: Choose the painting you will place next.
    nextrestart:
        description: Gives you the amount of time until the next restart
    lock-horse:
        description: Lock a horse so that only the owner can ride it.
        usage: |
            /lock-horse: Lock the next horse owned by you that you right click on.
    unlock-horse:
        description: Unlock a horse so that players other than the owner can ride it.
        usage: |
            /unlock-horse: Unlock the next horse owned by you that you right click on.
    untame:
        description: Untame a pet that you own.
        usage: |
            /untame: Untame the next pet owned by you that you right click on.
        