name: KitchenSink
version: 0.3
author: Travis Watkins
main: nu.nerd.kitchensink.KitchenSink
softdepend: [WorldGuard]
permissions:
    kitchensink.list:
        description: List online players
        default: true
    kitchensink.lag:
        description: Show lag stats
        default: op
    kitchensink.unenchant:
        description: Remove enchants from current item
        default: op
    kitchensink.delinventory:
        description: Remove a players inventory
        default: op
description: 

commands:
    unenchant:
        description: Remove enchants from current item
        permission: kitchensink.unenchant
    lag:
        description: Get current TPS and memory stats
    list:
        description: List currently online players
        permission: kitchensink.list
        usage: |
           /list: Show online players
    delinventory:
        description: Remove a players inventory
        permission: kitchensink.delinventory
        usage: |
           /delinventory <player>: Delete players inventory